### ISSUE TITLE
Logging a warning if you add a UI object with a name that already exists would be nice

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#103] opened 2013-12-18 10:47 UTC
This is because if the name already exists, the object doesn't get recreated, even though you "make a new" object. Causing the incorrect image to be used etc.

**Comment by GlenDC** [comment] 2013-12-18 18:39
Why wouldn't it get recreated? It add's it to a vector so i see now reason why not. I can and will log a warning if this happens but i don't seem to understand your problem completely.

**Comment by GlenDC** [comment] 2013-12-18 19:00
Problem has been resolved now I think, however I wont close the issue until we talked in person about this problem.

**Comment by GlenDC** [comment] 2013-12-19 13:55
Found the problem: 
In textureManager you get the ID of the texture based on the name. 
The problem is that you are not using unique names for your textures, because of this you will get always the first ID in the map and so your screwed. So what you need is unique texture names (For UIObjects there are constructors for that that allow you to define the sprite name(s).

I'm going to close the issue.

**Closed as completed by GlenDC** 2013-12-19 13:55 UTC
Labels: bug, enhancement
